main/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import *

urlpatterns = [
    path('', home, name='home'),
    path('login/', loginPage, name='login'),
    path('register/', registerPage, name='register'),
    path('check-valid-name/', check_name, name='check-name'),
    path('logout/', logoutUser, name='logout'),
    path('create-post/', createPost, name='create-post'),
    path('post/<int:pk>/', postDetail, name='post'),
    path('update-post/<int:pk>/', updatePost, name='update-post'),
    path('delete-post/<int:pk>/', deletePost, name='delete-post'),
    path('p/<slug:slug>/', userProfile, name='profile'),
    path('favorite/<slug:slug>/', favoritePost, name='favorite'),
    path('update-user/', updateUser, name='update-user'),
    path('delete-comment/<int:pk>/', deleteComment, name='delete-comment'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/',PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',PasswordResetCompleteView.as_view(),name='password_reset_complete')
]

parameters/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True, unique=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)
    avatar = models.ImageField(null=True, default="avatar.svg")
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []


    class Meta:
        verbose_name = 'CustomUser'
        verbose_name_plural = 'CustomUsers'


class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='sub_name')


    class Meta:
        verbose_name = 'Subscriber'
        verbose_name_plural = 'Subscribers'

    def __str__(self):
        return self.name.name


class Topic(models.Model):
    name = models.CharField(max_length=200)


    class Meta:
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(null=True, upload_to='Posts/%Y/%m/%d')
    title = models.CharField(max_length=200)
    description =  models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['-updated', '-created']
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.user.username


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Like'
        verbose_name_plural = 'Likes'

    def __str__(self):
        return self.post.user


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.user

main/forms.py
from django.forms import ModelForm, CharField, PasswordInput, EmailInput, TextInput, Textarea, FileInput
from django.contrib.auth.forms import UserCreationForm
from .models import *


class CreateUserForm(UserCreationForm):
    name = CharField(widget=TextInput(attrs={
        'class': 'form-control',
                'type': 'name',
                'placeholder': '@Name',
                'aria-describedby': 'basic-addon1',
                'name': 'name',
                'id': 'name'
    }))

    username = CharField(widget=TextInput(attrs={
                'class': 'form-control',
                'type': 'name',
                'placeholder': 'Username',
                'aria-describedby': 'basic-addon1'
            }))
    email = CharField(widget=EmailInput(attrs={
                'class': 'form-control',
                'type': 'email',
                'placeholder': 'Email@example.com',
                'aria-describedby': 'basic-addon2'
            }))
    password1 = CharField(widget=PasswordInput(attrs={
        'class': 'form-control',
                'type': 'password',
                'placeholder': 'Password',
                'for': 'form3Example4c'
    }))
    password2 = CharField(widget=PasswordInput(attrs={
        'class': 'form-control',
                'type': 'password',
                'placeholder': 'Password',
                'for': 'form3Example4c'
    }))
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'image', 'description']
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control form-control-lg',
                'type': 'text',

            }),
            'description': Textarea(attrs={
                'class': 'form-control form-control-lg',
                'type': 'text',

            }),
            'image': FileInput(attrs={
                'type': 'file',
                'class': 'form-control',

            }),
        }


class CommentForm(ModelForm):
    
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': Textarea(attrs={
                'value':'',
                'class':'form-control',
                'id':'comment_input'
            })
        }

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http import JsonResponse
from django.contrib import messages
from django.db.models import Q


# Login Page
def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username OR password does not exit')

    context = {'page': page}
    return render(request, 'main/login.html', context)

# Register Page
def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')
    return render(request, 'main/register.html', {'form': form})

# Logout User
def logoutUser(request):
    logout(request)
    return redirect('home')

# Check User Name
def check_name(request):
    username = request.GET.get('name')
    response = {
        'is_taken': User.objects.filter(name__iexact=username).exists()
    }
    return JsonResponse(response)

# Home Page
@login_required(login_url='login')
def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    posts = Post.objects.filter(
        Q(title__icontains=q) |
        Q(description__icontains=q)
    )
    if request.method == 'POST' and 'like' in request.POST:
        like = request.POST.get('like')
        post = Post.objects.get(id=like)
        try:
            like = Like.objects.get(user=request.user, post=post)
            like.delete()
        except:
            Like.objects.create(user = request.user, post=post)

    post_count = posts.count()
    likes = {}

    for i in posts:
        if not Like.objects.filter(user = request.user, post = i):
            likes[i] = False
        else:
            likes[i] = True


    context = {'posts': posts,
               'post_count': post_count,
               'likes':likes,
               }
    return render(request, 'main/home.html', context)

# Create Post Page
@login_required(login_url='login')
def createPost(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('home')
    context = {'form': form}
    return render(request, 'main/create_post.html', context)

# Update Post Page
@login_required(login_url='login')
def updatePost(request, pk):
    page = 'update'
    post = Post.objects.get(id=pk)
    form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('home')
    context = {'form': form}
    return render(request, 'main/create_post.html', context)

# User Page
@login_required(login_url='login')
def userProfile(request, slug):
    users = User.objects.all()
    user = User.objects.get(name=slug)
    if request.method == 'POST' and 'follow' in request.POST:
        try:
            follow = Subscriber.objects.get(user=user, name=request.user)
            follow.delete()
        except:
            Subscriber.objects.create(user=user, name=request.user)
    posts = user.post_set.filter(user=user)
    total_posts = posts.count()
    total_subscribers = user.subscriber_set.filter(user=user).count()
    subscribers = user.subscriber_set.filter(user=user)
    user_subs = Subscriber.objects.filter(user = user)
    subscribes = Subscriber.objects.filter(name=user)
    total_subscribes = subscribes.count()
    subscribe = {}

    for i in users:
        if not Subscriber.objects.filter(name = request.user, user = i):
            subscribe[i] = False
        else:
            subscribe[i] = True
    context = {'user': user,
               'posts': posts,
               'mysubscribes':subscribes,
               'total_subscribes':total_subscribes,
               'total_subscribers':total_subscribers,
               'subscribers':subscribers,
               'total_posts':total_posts,
               'all_subs':user_subs,
               'subscribe':subscribe}
    return render(request, 'main/profile.html', context)

# Favorite Posts Page
@login_required(login_url='login')
def favoritePost(request, slug):
    posts = Post.objects.all()
    user = User.objects.get(name=slug)
    my_likes = Like.objects.filter(user__name=user.name)
    if request.method == 'POST' and 'like' in request.POST:
        like = request.POST.get('like')
        post = Post.objects.get(id=like)
        try:
            like = Like.objects.get(user=request.user, post=post)
            like.delete()
        except:
            Like.objects.create(user = request.user, post=post)
        return redirect('favorite', slug=user.name)
    likes = {}

    for i in posts:
        if not Like.objects.filter(user = request.user, post = i):
            likes[i] = False
        else:
            likes[i] = True
    return render(request, 'main/favorite.html', {'my_likes': my_likes, 'likes':likes})

# Update User Page
@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('profile', slug=user.name)

    return render(request, 'main/update_user.html', {'form': form})

# Delete Post
@login_required(login_url='login')
def deletePost(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()
    return redirect('home')

# Post Detail Page
@login_required(login_url='login')
def postDetail(request, pk):
    post = Post.objects.get(id=pk)
    related_posts = Post.objects.filter(Q(title__contains=post.title))
    comments = post.comment_set.all()
    total_comments = comments.count()
    form = CommentForm()
    if request.method == 'POST' and request.is_ajax():
        form = CommentForm(request.POST)
        form.instance.user = request.user
        form.instance.post = post
        if form.is_valid():
            form.save()
            
    context = {'post': post,
                'comments':comments, 'form': form,
                'total_comments':total_comments,
                'related_posts':related_posts}
    return render(request, 'main/post_detail.html', context)

# Delete Comment
@login_required(login_url='login')
def deleteComment(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.delete()
    return redirect('post', pk=comment.post.id)

main/templates/main/create_post.html
<!-- CREATE POST TEMPLATE -->
{% extends 'base.html' %}
{% block title %}Create post{% endblock %}
{% block content %}
<section >
  <div class="mask d-flex align-items-center h-100 gradient-custom-3 mt-4">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
                {% if page == 'update' %}
              <h2 class="text-uppercase text-center mb-5">Update post</h2>
              {% else %}
              <h2 class="text-uppercase text-center mb-5">Create post</h2>
              {% endif %}
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-outline mb-4">
                  <div class="input-group mb-3">
                    <label class="input-group-text" for="inputGroupFile01">Image</label>
                    {{ form.image }}
                  </div>
                  <label class="form-label" for="form3Example1cg">Image</label>
                </div>
                <div class="form-outline mb-4">
                  {{ form.title }}
                  <label class="form-label" for="form3Example1cg">Name</label>
                </div>
                <div class="form-outline mb-4">
                  {{ form.description }}
                  <label class="form-label" for="form3Example3cg">Content</label>
                </div>

                <div class="d-flex justify-content-center">
                  <button type="submit"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Create</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    {% endblock %}

main/templates/main/favorite.html
<!-- HOME TEMPLATE -->
{% extends 'base.html' %}
{% block title %}Favorite{% endblock %}
    {% load static %}
    {% block content %}
    <main>
    <div class="album py-5 bg-light">
        <div class="container">
    
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for like in my_likes %}
            <div class="col">
              <div class="card shadow-sm">
                <img src="{{ like.post.image.url }}" alt="" class="bd-placeholder-img card-img-top " width="100%" height="225">
                
                <div class="card-body">
                    <p class="card-text"><h5>{{ like.post.title|truncatewords:4 }}</h5></p>
                  <p class="card-text">{{ like.post.description|truncatewords:10 }}.</p>
                  <small class="text-muted">Posted {{ like.post.created|timesince }} ago</small>
                  <p class="card-text"> <a href="{% url 'profile' like.post.user.name %}"><img src="{% if like.post.user.avatar.url %}{{ like.post.user.avatar.url }}{% else %}{% static 'main/images/avatar.svg' %}{% endif %}"  width="32" height="32" class="rounded-circle">@{{ like.post.user }}</a></p>
                  <small class="text-muted">Comments: {{ like.post.comment_set.count }}</small> 
                  <small class="text-muted">Likes: {{ like.post.like_set.count }}</small> 
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">


                      <form method="post" >
                            {% csrf_token %}

                            <input type="hidden" name="like" value="{{ like.post.id }}">
                            <button type="submit" class="btn btn-primary">
                              {%for k, v in likes.items%}
                              {%if k == post%}
                              {%if v%}
                              unlike
                              {%else%}
                              like
                              {%endif%}
                              {%endif%}
                              {%endfor%}
                            </button>

                      </form>

                        {% if like.post.user == request.user or like.request.user.is_superuser %}
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Delete
                          </button>
                          <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Delete post</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="" method="post">
                                    <div class="modal-body">
                                            {% csrf_token %}
                                            <p>Do you want to delete {{ like.post.title }}?</p> 
                                    </div>
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a type="submit" href="{% url 'delete-post' like.post.id %}" class="btn btn-danger">Delete</a>
                                    </form>
                                </div>
                            </div>
                            </div>

                        </div>
                    
                      <a href="{% url 'update-post' like.post.id %}" class="btn btn-info">Update</a>

                        {% endif %}
                        <a href="{% url 'post' like.post.id %}" class="btn btn-primary">View</a>



                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% empty %}
            <h5>Empty</h5>
            {% endfor %}
          </div>
        </div>
      </div>
    
    </main>
    {% endblock %}

main/templates/main/home.html
<!-- HOME TEMPLATE -->
{% extends 'base.html' %}
{% block title %}Welcome-Senpai{% endblock %}
    {% load static %}
    {% block content %}
    <main>
    <div class="album py-5 bg-light">
        <div class="container">
    
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for post in posts %}
            <div class="col">
              <div class="card shadow-sm">
                <img src="{{ post.image.url }}" alt="" class="bd-placeholder-img card-img-top " width="100%" height="225">
                
                <div class="card-body">
                    <p class="card-text"><h5>{{ post.title|truncatewords:4 }}</h5></p>
                  <p class="card-text">{{ post.description|truncatewords:10 }}.</p>
                  <small class="text-muted">Posted {{ post.created|timesince }} ago</small>
                  <p class="card-text"> <a href="{% url 'profile' post.user.name %}"><img src="{% if post.user.avatar.url %}{{ post.user.avatar.url }}{% else %}{% static 'main/images/avatar.svg' %}{% endif %}"  width="32" height="32" class="rounded-circle">@{{ post.user }}</a></p>
                  <small class="text-muted">Comments: {{ post.comment_set.count }}</small> 
                  <small class="text-muted">Likes: {{ post.like_set.count }}</small> 
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">


                      <form method="post">
                            {% csrf_token %}

                            <input type="hidden" name="like" value="{{ post.id }}">
                      
                            <button type="submit" class="btn btn-primary">
                              {%for k, v in likes.items%}
                              {%if k == post%}
                              {%if v%}
                              unlike
                              {%else%}
                              like
                              {%endif%}
                              {%endif%}
                              {%endfor%}
                            </button>
                            
                      </form>

                        {% if post.user == request.user or request.user.is_superuser %}
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Delete
                          </button>
                          <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Delete post</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="" method="post">
                                    <div class="modal-body">
                                            {% csrf_token %}
                                            <p>Do you want to delete {{ post.title }}?</p> 
                                    </div>
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a type="submit" href="{% url 'delete-post' post.id %}" class="btn btn-danger">Delete</a>
                                    </form>
                            
                                </div>
                            </div>
                            </div>

                        </div>
                    
                      <a href="{% url 'update-post' post.id %}" class="btn btn-info">Update</a>

                        {% endif %}
                        <a href="{% url 'post' post.id %}" class="btn btn-primary">View</a>



                    </div>
                    
                  </div>
                </div>
              
              </div>
            </div>
            {% empty %}
            <h5>Empty</h5>
            {% endfor %}
          </div>
        </div>
      </div>
    
    </main>
    {% endblock %}

main/templates/main/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <title>Login</title>
</head>
<body>

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
            <a href="{% url 'home' %}" class="btn btn-sm btn-outline-secondary">Go back</a>
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign in</p>
  
                  <form class="mx-1 mx-md-4" method="post">
                    {% csrf_token %}
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" id="form3Example1c" class="form-control" name="username"/>
                        <label class="form-label" for="form3Example1c">Your Name</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        
                        <input type="password" id="form3Example4cd" class="form-control" name="password"/>
                        <label class="form-label" for="form3Example4cd">Password</label>
                      </div>
                    </div>
                    {% if messages %}
                    <div class="alert alert-danger" role="alert">
                      {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="form-check d-flex justify-content-center mb-5">
                      <input class="form-check-input me-2" type="checkbox" checked value="" id="form2Example3c" name="remember"/>
                      <label class="form-check-label" for="form2Example3">
                        Remember me
                      </label>
                    </div>
                    <div class="form-check d-flex justify-content-center mb-5">
          
                        Don't have an account? <a href="{% url 'register' %}">Sign up</a>

                    </div>
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Login</button>
                    </div>
            
                  </form>
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html>

main/templates/main/password_change_done.html
{% extends "base.html" %}
{% block title %}Password changed{% endblock %}
{% block content %}
<h1>Password changed</h1>
<p>Your password has been successfully changed.</p>
{% endblock %}

main/templates/main/password_change_form.html
{% extends "base.html" %}
{% block title %}Change you password{% endblock %}
{% block content %}
<h1>Change you password</h1>
<p>Use the form below to change your password.</p>
<form action="." method="post">
{{ form.as_p }}
<p><input type="submit" value="Change">Change</p>
{% csrf_token %}
</form>
{% endblock %}

main/templates/main/search.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

main/templates/main/update_user.html
{% extends 'base.html' %}
{% block content %}
<form class="form" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in form %}
    <div class="form__group">
      <label for="profile_pic">{{field.label}}</label>
      {{field}}
    </div>
    {% endfor %}


    <div class="form__action">
      <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
      <button class="btn btn--main" type="submit">Update</button>
    </div>
  </form>
  <a href="{% url 'password_change' %}">Change password</a>
{% endblock %}